version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - /opt/config/secret.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: data_warehouse

  app:
    build: .
    restart: always
    ports:
      -  target: 8080
         published: 80
    env_file:
      - /opt/config/secret.env
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
